/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";
import gsap from "gsap";
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/64f1a714fe61576b46f27ca2.glb"
  );

  const { message, onMessagePlayed, chat } = useChat();
  const avatarGroupRef = useRef();
  const [lipsync, setLipsync] = useState();
  const [idleMovement, setIdleMovement] = useState(true);
  const [modelLoaded, setModelLoaded] = useState(false);
  const [animationsLoaded, setAnimationsLoaded] = useState(false);
  const animationsRef = useRef(null);
  const actionsRef = useRef({});
  const mixerRef = useRef(null);
  const [currentAnimation, setCurrentAnimation] = useState("Idle");

  // Load animations with error handling
  useEffect(() => {
    let mounted = true;
    
    const loadAnimations = async () => {
      try {
        // Set up DRACOLoader
        const dracoLoader = new DRACOLoader();
        dracoLoader.setDecoderPath('/draco/');
        // Try JS decoder first, but allow fallback to WASM if needed
        dracoLoader.setDecoderConfig({ type: 'js' }); 
        
        // Add a small delay to ensure decoder files are registered
        await new Promise(resolve => setTimeout(resolve, 100));
        
        // Configure GLTFLoader with DRACOLoader
        const loader = new GLTFLoader();
        loader.setDRACOLoader(dracoLoader);
        
        const gltf = await new Promise((resolve, reject) => {
          loader.load(
            "/models/animations.glb",
            resolve,
            undefined,
            reject
          );
        });
        
        if (!mounted) return;
        
        console.log("Animations loaded:", gltf.animations);
        animationsRef.current = gltf.animations;
        setAnimationsLoaded(true);
        
        // Initialize animation mixer
        if (group.current) {
          mixerRef.current = new THREE.AnimationMixer(group.current);
          
          // Create actions dictionary
          const actions = {};
          animationsRef.current.forEach((clip) => {
            try {
              const action = mixerRef.current.clipAction(clip);
              actions[clip.name] = action;
              console.log("Created action for:", clip.name);
            } catch (error) {
              console.error(`Failed to create action for animation ${clip.name}:`, error);
            }
          });
          actionsRef.current = actions;
          
          // Start default animation
          startAnimation("Idle");
        }
      } catch (error) {
        console.error("Error loading animations:", error);
      }
    };
    
    loadAnimations();
    
    return () => {
      mounted = false;
      // Cleanup animations
      if (mixerRef.current) {
        try {
          mixerRef.current.stopAllAction();
        } catch (error) {
          console.error("Error stopping animations on unmount:", error);
        }
      }
    };
  }, []);

  // Indicate when model is loaded
  useEffect(() => {
    if (nodes && materials && scene) {
      console.log("Avatar model loaded successfully");
      setModelLoaded(true);
    }
  }, [nodes, materials, scene]);

  // Add a simple visible object for debugging
  const debugSphereRef = useRef();
  
  // Initialize animation for subtle idle movement - now using custom animation classes from Tailwind
  useEffect(() => {
    // Don't start animations until model is loaded
    if (!avatarGroupRef.current || !modelLoaded) return;
    
    // Force idle movement to always be true
    setIdleMovement(true);
    
    // Apply animations through DOM manipulation - with proper THREE.js object properties
    // THREE.js objects don't have classList methods, so we use direct property manipulation
    if (avatarGroupRef.current) {
      // Add custom animations through inline styles with transform properties
      const applyIdleAnimation = () => {
        if (!avatarGroupRef.current) return;
        
        // Use requestAnimationFrame for smooth animation
        const breathingSpeed = 0.001; // Increased for more noticeable movement
        const swaySpeed = 0.0005; // Increased for more noticeable movement
        let time = 0;
        
        const animate = () => {
          time += 1;
          
          if (avatarGroupRef.current) {
            // Breathing motion - enhanced
            const breathingMotion = Math.sin(time * breathingSpeed) * 0.08;
            // Swaying motion - enhanced
            const swayMotion = Math.sin(time * swaySpeed) * 0.1;
            // Slight head tilt - new
            const tiltMotion = Math.sin(time * breathingSpeed * 0.7) * 0.03;
            
            // Apply transformations directly to Three.js object
            avatarGroupRef.current.position.y = breathingMotion;
            avatarGroupRef.current.rotation.y = swayMotion;
            avatarGroupRef.current.rotation.z = tiltMotion;
          }
          
          animationFrameId = requestAnimationFrame(animate);
        };
        
        let animationFrameId = requestAnimationFrame(animate);
        
        // Return cleanup function
        return () => {
          cancelAnimationFrame(animationFrameId);
          if (avatarGroupRef.current) {
            avatarGroupRef.current.position.y = 0;
            avatarGroupRef.current.rotation.y = 0;
            avatarGroupRef.current.rotation.z = 0;
          }
        };
      };
      
      // Start the animation
      const cleanupAnimation = applyIdleAnimation();
      
      // Return cleanup function
      return () => {
        cleanupAnimation();
      };
    }
  }, [modelLoaded]); // Remove idleMovement dependency to ensure animation always runs

  useEffect(() => {
    console.log(message);
    if (!message) {
      if (animationsLoaded && mixerRef.current) {
        setCurrentAnimation("Idle");
      }
      return;
    }
    
    // Animate avatar when a new message comes in - using THREE.js properties directly
    if (avatarGroupRef.current) {
      // Apply hop animation
      const applyHopAnimation = () => {
        const duration = 600; // 600ms
        const startTime = Date.now();
        const maxHeight = 0.2;
        
        const animate = () => {
          const elapsed = Date.now() - startTime;
          const progress = Math.min(elapsed / duration, 1);
          
          // Simple easing function
          const easeOut = function(t) {
            return 1 - Math.pow(1 - t, 2);
          };
          
          // Apply hop animation
          if (progress < 1) {
            const height = maxHeight * Math.sin(progress * Math.PI) * easeOut(progress);
            avatarGroupRef.current.position.y = height;
            requestAnimationFrame(animate);
          } else {
            avatarGroupRef.current.position.y = 0;
          }
        };
        
        requestAnimationFrame(animate);
      };
      
      applyHopAnimation();
    }
    
    // Pause idle animations during specific animations
    if (message.animation !== "Idle") {
      setIdleMovement(false);
      
      // Resume idle animations after the message animation completes
      const animationDuration = message.animation === "Dance" ? 10000 : 4000; // Just an example - adjust as needed
      setTimeout(() => setIdleMovement(true), animationDuration);
    }
    
    if (animationsLoaded && mixerRef.current) {
      setCurrentAnimation(message.animation);
    }
    
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);
    
    if (message.audio) {
      const audio = new Audio("data:audio/mp3;base64," + message.audio);
      audio.play();
      setAudio(audio);
      audio.onended = onMessagePlayed;
    }
  }, [message, animationsLoaded, onMessagePlayed]);

  // Handle animation changes
  useEffect(() => {
    if (!animationsLoaded || !currentAnimation) return;
    
    console.log("Changing animation to:", currentAnimation);
    startAnimation(currentAnimation);
    
  }, [currentAnimation, animationsLoaded]);

  const group = useRef();

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();
  const [lastMousePosition, setLastMousePosition] = useState({ x: 0, y: 0 });
  
  // Add tracking mouse cursor for the avatar to follow - replace GSAP with direct THREE.js transform manipulation
  useEffect(() => {
    const handleMouseMove = (event) => {
      try {
        // Only update if the mouse has moved significantly
        if (Math.abs(event.clientX - lastMousePosition.x) > 20 ||
            Math.abs(event.clientY - lastMousePosition.y) > 20) {
            
          setLastMousePosition({ x: event.clientX, y: event.clientY });
          
          if (avatarGroupRef.current) {
            // Calculate normalized mouse position (-1 to 1)
            const mouseX = (event.clientX / window.innerWidth) * 2 - 1;
            const mouseY = -(event.clientY / window.innerHeight) * 2 + 1;
            
            // Use direct property manipulation for THREE.js objects
            const targetRotationX = mouseY * 0.1;
            const targetRotationY = mouseX * 0.2;
            
            // Smoothly transition to target rotations
            gsap.to(avatarGroupRef.current.rotation, {
              x: targetRotationX,
              y: targetRotationY,
              duration: 0.8,
              ease: "power2.out"
            });
          }
        }
      } catch (error) {
        console.error("Error in mouse tracking:", error);
      }
    };
    
    window.addEventListener('mousemove', handleMouseMove);
    
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
    };
  }, [lastMousePosition]);

  // Animation frame update
  useFrame((state, delta) => {
    try {
      // Update animation mixer
      if (mixerRef.current) {
        mixerRef.current.update(delta);
      }
      
      if (!setupMode && nodes && nodes.EyeLeft && nodes.EyeLeft.morphTargetDictionary) {
        // Update facial expressions
        Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
          const mapping = facialExpressions[facialExpression];
          if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
            return; // eyes wink/blink are handled separately
          }
          if (mapping && mapping[key]) {
            try {
              lerpMorphTarget(key, mapping[key], 0.1);
            } catch (error) {
              // Morph target errors are common and not critical, so just log silently
              console.debug(`Error updating morph target ${key}:`, error);
            }
          } else {
            try {
              lerpMorphTarget(key, 0, 0.1);
            } catch (error) {
              console.debug(`Error resetting morph target ${key}:`, error);
            }
          }
        });

        try {
          lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
          lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);
        } catch (error) {
          console.debug("Error updating eye blink:", error);
        }

        // LIPSYNC
        if (setupMode) {
          return;
        }

        const appliedMorphTargets = [];
        if (message && lipsync && audio && audio.currentTime) {
          try {
            const currentAudioTime = audio.currentTime;
            for (let i = 0; i < lipsync.mouthCues.length; i++) {
              const mouthCue = lipsync.mouthCues[i];
              if (
                currentAudioTime >= mouthCue.start &&
                currentAudioTime <= mouthCue.end
              ) {
                const visemeKey = corresponding[mouthCue.value];
                if (visemeKey) {
                  appliedMorphTargets.push(visemeKey);
                  lerpMorphTarget(visemeKey, 1, 0.2);
                  break;
                }
              }
            }
          } catch (error) {
            console.debug("Error in lipsync processing:", error);
          }
        }

        // Reset non-active visemes
        Object.values(corresponding).forEach((value) => {
          if (appliedMorphTargets.includes(value)) {
            return;
          }
          try {
            lerpMorphTarget(value, 0, 0.1);
          } catch (error) {
            console.debug(`Error resetting viseme ${value}:`, error);
          }
        });
      }
    } catch (error) {
      console.error("Error in animation frame update:", error);
    }
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: currentAnimation,
      options: animationsRef.current ? animationsRef.current.map((a) => a.name) : [],
      onChange: (value) => {
        if (animationsLoaded) {
          setCurrentAnimation(value);
        }
      },
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      if (!nodes || !nodes.EyeLeft) return;
      
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () => {
    if (!nodes || !nodes.EyeLeft || !nodes.EyeLeft.morphTargetDictionary) {
      return {};
    }
    
    return Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    );
  });

  useEffect(() => {
    let blinkTimeout;
    
    const nextBlink = () => {
      try {
        blinkTimeout = setTimeout(() => {
          setBlink(true);
          
          // Use GSAP for blinking animation with proper cleanup
          const blinkDuration = gsap.delayedCall(0.15, () => {
            setBlink(false);
            nextBlink();
          });
          
          return () => {
            blinkDuration.kill();
          };
        }, THREE.MathUtils.randInt(1000, 5000));
      } catch (error) {
        console.error("Error in blink animation:", error);
        // Retry blink after error
        setTimeout(nextBlink, 3000);
      }
    };
    
    nextBlink();
    
    return () => {
      if (blinkTimeout) {
        clearTimeout(blinkTimeout);
      }
    };
  }, []);

  // Add this helper function to start animations
  const startAnimation = (animationName) => {
    try {
      if (!actionsRef.current) {
        console.warn("Actions not initialized yet");
        return;
      }
      
      console.log("Available animations:", Object.keys(actionsRef.current));
      
      // Stop all current animations
      Object.values(actionsRef.current).forEach(action => {
        action.fadeOut(0.5);
      });
      
      // Start the requested animation
      const action = actionsRef.current[animationName];
      if (action) {
        console.log("Starting animation:", animationName);
        action.reset().fadeIn(0.5).play();
        setCurrentAnimation(animationName);
      } else {
        console.warn(`Animation "${animationName}" not found`);
        // Try to start Idle as fallback
        if (animationName !== "Idle" && actionsRef.current["Idle"]) {
          console.log("Starting fallback Idle animation");
          actionsRef.current["Idle"].reset().fadeIn(0.5).play();
          setCurrentAnimation("Idle");
        }
      }
    } catch (error) {
      console.error("Error starting animation:", error);
    }
  };

  return (
    <group {...props} dispose={null} ref={group}>
      {/* Debug sphere to verify rendering */}
      <mesh ref={debugSphereRef} position={[0, 1.5, 0]} visible={!modelLoaded}>
        <sphereGeometry args={[0.5, 32, 32]} />
        <meshStandardMaterial color="hotpink" />
      </mesh>
      
      {/* Only render the avatar if all assets are loaded */}
      {modelLoaded && (
        <group 
          ref={avatarGroupRef} 
          position={[0, 0, 0]} 
          scale={1}
        >
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            skeleton={nodes.Wolf3D_Body.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            skeleton={nodes.Wolf3D_Hair.skeleton}
            castShadow
          />
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            castShadow
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
        </group>
      )}
    </group>
  );
}

useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/animations.glb");
